# Generated by Django 5.0.7 on 2024-08-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('nome_social', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('mae', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=20)),
                ('cor_raca', models.CharField(choices=[('', 'Selecione'), ('AMA', 'Amarela'), ('IND', 'Índigena'), ('BRA', 'Branca'), ('PAR', 'Pardo'), ('PRE', 'Preta')], max_length=6)),
                ('escolaridade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisao', models.BooleanField()),
                ('prisao_justificativa', models.CharField(blank=True, max_length=50, null=True)),
                ('prisao_familiar', models.BooleanField()),
                ('prisao_familiar_justificativa', models.CharField(blank=True, max_length=50, null=True)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saude', models.BooleanField()),
                ('saude_just', models.CharField(blank=True, max_length=50, null=True)),
                ('tratmentPS', models.BooleanField()),
                ('tratmentPS_just', models.CharField(blank=True, max_length=50, null=True)),
                ('medica_ctL', models.BooleanField()),
                ('medica_ctL_jus', models.CharField(blank=True, max_length=50, null=True)),
                ('Deficiencia', models.BooleanField()),
                ('Deficiencia_just', models.CharField(blank=True, max_length=50, null=True)),
                ('drogas_uso', models.IntegerField(blank=True, null=True)),
                ('drogas_jus', models.CharField(blank=True, max_length=50, null=True)),
                ('tratmento', models.BooleanField()),
                ('tratmento_jus', models.CharField(blank=True, max_length=50, null=True)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesTecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=255)),
                ('juiz', models.CharField(max_length=50)),
                ('medida', models.CharField(max_length=50)),
                ('tipo_penal', models.CharField(max_length=50)),
                ('violencia_dome', models.CharField(max_length=50)),
                ('violencia_dome_nom', models.CharField(max_length=50)),
                ('grau_paren', models.CharField(max_length=50)),
                ('reincidencia', models.BooleanField()),
                ('sugest_trb', models.CharField(max_length=1)),
                ('sugest_enc', models.CharField(max_length=1)),
                ('cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cidadao')),
            ],
        ),
    ]
