# Generated by Django 5.0.7 on 2024-08-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_historicocriminal_prisao_familiar_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocriminal',
            name='ja_esteve_preso',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='prisao_familiar',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='reincidencia',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, null=True),
        ),
    ]
