# Generated by Django 5.0.7 on 2024-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cidadao_remuneracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='idade',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='remuneracao',
            field=models.CharField(choices=[('Empregado', 'Empregado'), ('Desempregado', 'Desempregado'), ('Trabalhador Rural', 'Trabalhador Rural'), ('Autônomo', 'Autônomo'), ('Funcionario Publico', 'Funcionario Publico'), ('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Afastado/INSS', 'Afastado/INSS'), ('Do lar', 'Do lar'), ('Estudante', 'Estudante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='prisao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='deficiencia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='medicacao_controlada',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='saude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='tratamento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
