# Generated by Django 5.0.7 on 2024-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cidadao_idade_alter_cidadao_remuneracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='renda_individual',
            field=models.CharField(choices=[('Menos de um salario minimo', 'Menos de um salario minimo'), ('1 salario minimo', '1 salario minimo'), ('2 a 3 salarios minimos', '2 a 3 salarios minimos'), ('Mais de 4 salarios minimos', 'Mais de 4 salarios minimos'), ('Recebo bolsa familia', 'Recebo bolsa familia'), ('Dependo financeiramente de outras pessoas', 'Dependo financeiramente de outras pessoas')], default=1.0, max_length=50),
            preserve_default=False,
        ),
    ]
