# Generated by Django 5.0.7 on 2024-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cidadao_renda_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cor_raca',
            field=models.CharField(choices=[('', 'Selecione'), ('AMARELA', 'Amarela'), ('INDIO', 'Índigena'), ('BRANCO', 'Branca'), ('PARDO', 'Pardo'), ('PRETA', 'Preta')], max_length=8),
        ),
    ]
