# Generated by Django 5.0.7 on 2024-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cidadao_cor_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoescomplementares',
            name='tecnico_responsavel',
            field=models.CharField(default=1.0, max_length=200),
            preserve_default=False,
        ),
    ]
