# Generated by Django 5.0.7 on 2024-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_informacoescomplementares_tecnico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default=1.0, max_length=255),
            preserve_default=False,
        ),
    ]
