# Generated by Django 5.0.7 on 2024-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_formulario_acompanhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoescomplementares',
            name='data',
            field=models.CharField(default=1.0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoescomplementares',
            name='evolucao_percepcoes',
            field=models.CharField(default=1.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoescomplementares',
            name='tecnico',
            field=models.CharField(default=1.0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='formulario_acompanhamento',
        ),
    ]
