# Generated by Django 5.0.7 on 2024-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_informacoescomplementares_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='remuneracao',
            field=models.CharField(choices=[('Empregado', 'Empregado'), ('Desempregado', 'Desempregado'), ('Trabalhador Rural', 'Trabalhador Rural'), ('Autônomo', 'Autônomo'), ('Funcionario Publico', 'Funcionario Publico'), ('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Afastado/INSS', 'Afastado/INSS'), ('Do lar', 'Do lar'), ('Estudante', 'Estudante')], default='', max_length=20),
        ),
    ]
