# Generated by Django 5.0.7 on 2024-08-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cidadao_remuneracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cor_raca',
            field=models.CharField(choices=[('', 'Selecione'), ('AMARELA', 'Amarela'), ('INDIO', 'Índigena'), ('BRANCO', 'Branca'), ('PARDO', 'Pardo'), ('PRETA', 'Preta')], max_length=8, verbose_name='Cor/Raça'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='idade',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='mae',
            field=models.CharField(max_length=50, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='remuneracao',
            field=models.CharField(blank=True, choices=[('Empregado', 'Empregado'), ('Desempregado', 'Desempregado'), ('Trabalhador Rural', 'Trabalhador Rural'), ('Autônomo', 'Autônomo'), ('Funcionario Publico', 'Funcionario Publico'), ('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Afastado/INSS', 'Afastado/INSS'), ('Do lar', 'Do lar'), ('Estudante', 'Estudante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='sexo',
            field=models.CharField(choices=[('', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')], default='selecione', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='cidadao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_criminais', to='core.cidadao'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='grau_de_parentesco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grau de parentesco da vitima'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='reincidencia',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, null=True, verbose_name='Relata reincidência?'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='sugest_encaminhamento',
            field=models.CharField(blank=True, choices=[('SASDH', 'SASDH'), ('NATERA-MP', 'NATERA-MP'), ('GRUPO NAA OU AA', 'GRUPO NAA OU AA'), ('INTERNAÇÃO EM COMUNIDADE TERAPÊUTICA', 'INTERNAÇÃO EM COMUNIDADE TERAPÊUTICA'), ('RETIRADA DE DOCUMENTOS-IML', 'RETIRADA DE DOCUMENTOS-IML'), ('CAPS-AD |||/CAPS-SAMAUMA', 'CAPS-AD |||/CAPS-SAMAUMA'), ('OUTROS', 'OUTROS')], max_length=36, null=True, verbose_name='Sugestão de encaminhamento'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='violencia_dome_nome_vitima',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome da vitima de violência domestica'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='violencia_domestica',
            field=models.CharField(blank=True, max_length=50, verbose_name='Em caso de violência domestica'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='deficiencia',
            field=models.CharField(default='', max_length=100, verbose_name='É portador de alguma deficiência'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='medicacao_controlada',
            field=models.CharField(default='', max_length=100, verbose_name='Faz uso de alguma medicação controlada?'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='saude',
            field=models.CharField(default='', max_length=255, verbose_name='Apresenta problemas de saude?'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='tratamento',
            field=models.CharField(default='', max_length=100, verbose_name='Já procurou tratamento?'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='tratamento_psiquiatrico',
            field=models.CharField(max_length=100, verbose_name='Faz ou fez tratamento psiquiatrico?'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='parentesco',
            field=models.CharField(default='', max_length=100),
        ),
    ]
