# Generated by Django 5.0.7 on 2024-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cidadao_cor_raca_alter_cidadao_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocriminal',
            name='prisao',
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='estado',
            field=models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], max_length=19),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='remuneracao',
            field=models.CharField(blank=True, choices=[('Empregado', 'Empregado'), ('Desempregado', 'Desempregado'), ('Trabalhador Rural', 'Trabalhador Rural'), ('Autônomo', 'Autônomo'), ('Funcionario Publico', 'Funcionario Publico'), ('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Afastado/INSS', 'Afastado/INSS'), ('Do lar', 'Do lar'), ('Estudante', 'Estudante')], max_length=20, verbose_name='Remuneração'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='drogas_uso',
            field=models.CharField(blank=True, choices=[('Álcool', 'Álcool'), ('Cigarro', 'Cigarro'), ('Maconha', 'Maconha'), ('Pasta Base', 'Pasta Base'), ('Cocaína', 'Cocaína'), ('Merla', 'Merla'), ('Crack', 'Crack'), ('Outras drogas', 'Outras drogas')], max_length=20, null=True, verbose_name='Faz ou já fez uso de'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='analise_descritiva',
            field=models.CharField(max_length=300, verbose_name='Análise descritiva'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='escolaridade_familiar',
            field=models.CharField(max_length=100, verbose_name='Grau de Escolaridade'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='evolucao_percepcoes',
            field=models.CharField(max_length=255, verbose_name='Evolução percepções'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='idade_familiar',
            field=models.CharField(default='0', max_length=3, verbose_name='Idade do familiar'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='nome_familiar',
            field=models.CharField(max_length=70, verbose_name='Nome de um familiar'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='ocupacao',
            field=models.CharField(max_length=100, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='parentesco',
            field=models.CharField(default='', max_length=100, verbose_name='Grau de parentesco'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='quantas_pessoas',
            field=models.CharField(max_length=100, verbose_name='Quantas pessoas moram com você ? (inclua você na contagem)'),
        ),
    ]
