# Generated by Django 5.0.7 on 2024-08-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_historicocriminal_prisao_alter_cidadao_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosaude',
            name='tratamento',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='', max_length=3, verbose_name='Já procurou tratamento?'),
        ),
    ]
