# Generated by Django 5.0.7 on 2024-08-28 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cidadao_moradia_situacao_cidadao_moradia_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicosaude',
            name='tratamento_psiquiatrico',
        ),
        migrations.AddField(
            model_name='cidadao',
            name='meu_campo_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicocriminal',
            name='meu_campo_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='medicacao_controlada_jus',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Especifique o tipo de medicação controlada'),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='meu_campo_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='saude_just',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Se apresenta problema de saúde qual?'),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='tratamento_psi',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=3, verbose_name='Faz ou fez tratamento psiquiatrico?'),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='tratamento_psi_jus',
            field=models.CharField(default=1.0, max_length=80, verbose_name='Especifique o tratamento psiquiatrico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoescomplementares',
            name='meu_campo_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='medicacao_controlada',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=3, verbose_name='Faz uso de alguma medicação controlada?'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='saude',
            field=models.CharField(default='Selecione', max_length=3, verbose_name=(('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não'))),
        ),
    ]
