# Generated by Django 5.0.7 on 2024-08-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_historicosaude_tratamento_psiquiatrico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidadao',
            old_name='meu_campo_data',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='historicocriminal',
            old_name='meu_campo_data',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='historicosaude',
            old_name='meu_campo_data',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='informacoescomplementares',
            old_name='meu_campo_data',
            new_name='data_criacao',
        ),
    ]
