# Generated by Django 5.0.7 on 2024-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_meu_campo_data_cidadao_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosaude',
            name='saude',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=3, verbose_name='Apresenta problemas de saude?'),
        ),
    ]
