# Generated by Django 5.0.7 on 2024-08-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_historicosaude_saude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocriminal',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='historicosaude',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='informacoescomplementares',
            name='data_criacao',
        ),
    ]
