# Generated by Django 5.0.7 on 2024-08-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_historicocriminal_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='data_criacao',
        ),
    ]
