# Generated by Django 5.0.7 on 2024-08-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
