# Generated by Django 5.0.7 on 2024-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='renda_individual',
            field=models.CharField(choices=[('MENOS DE UM SALARIO MINIMO', 'Menos de um salario minimo'), ('1 SALARIO MINIMO', '1 salario minimo'), ('2 A 3 SALARIOS MINIMOS', '2 a 3 salarios minimos'), ('MAIS DE 4 SALARIOS MINIMOS', 'Mais de 4 salarios minimos'), ('RECEBO BOLSA FAMILIA', 'Recebo bolsa familia'), ('DEPENDO FINANCEIRAMENTE DE OUTRAS PESSOAS', 'Dependo financeiramente de outras pessoas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='drogas_uso',
            field=models.CharField(blank=True, choices=[('ALCOOL', 'Álcool'), ('CIGARRO', 'Cigarro'), ('MACONHA', 'Maconha'), ('PASTA BASE', 'Pasta Base'), ('COCAINA', 'Cocaína'), ('MERLA', 'Merla'), ('CRACK', 'Crack'), ('OUTRAS DROGAS', 'Outras drogas')], max_length=20, null=True, verbose_name='Faz ou já fez uso de'),
        ),
    ]
