# Generated by Django 5.0.7 on 2024-08-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='usuario',
            field=models.ForeignKey(default=190, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
