# Generated by Django 5.0.7 on 2024-08-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_imagem_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
