# Generated by Django 5.0.7 on 2024-08-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
