# Generated by Django 5.0.7 on 2024-09-03 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
