# Generated by Django 5.0.7 on 2024-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_cidadao_data_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoescomplementares',
            name='data',
        ),
    ]
