# Generated by Django 5.0.7 on 2024-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_informacoescomplementares_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='escolaridade',
            field=models.CharField(choices=[('NAO ESCOLARIZADO', 'Não escolarizado'), ('FUNDAMENTAL INCOMPLETO', 'Fundamental incompleto'), ('FUNDAMENTAL COMPLETO', 'Fundamental completo'), ('MEDIO INCOMPLETO', 'Médio Incompleto'), ('MEDIO COMPLETO', 'Médio Completo'), ('SUPERIOR INCOMPLETO', 'Superior Incompleto'), ('SUPERIOR COMPLETO', 'Superior Completo'), ('POS GRADUAÇÃO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('POS-DOUTORADO', 'Pós Doutorado'), ('NÃO DETERMINADO', 'Não determinado')], default='selecione', max_length=50),
        ),
    ]
