# Generated by Django 5.0.7 on 2024-09-04 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_informacoescomplementares_medida_cumprimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoescomplementares',
            name='evolucao_percepcoes',
        ),
        migrations.RemoveField(
            model_name='informacoescomplementares',
            name='tecnico_responsavel',
        ),
        migrations.AddField(
            model_name='informacoescomplementares',
            name='motivo_saida',
            field=models.CharField(choices=[('NAO DEFINIDO', 'NÃO DEFINIDO'), ('CUMPRIMENTO INTEGRAL', 'CUMPRIMENTO INTEGRAL'), ('DESCUMPRIMENTO', 'DESCUMPRIMENTO'), ('PRISAO', 'PRISÃO'), ('OUTRO', 'OUTRO')], default='nao definido', max_length=40, verbose_name='Motivo de saida'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='tip_penal',
            field=models.CharField(choices=[('', 'Selecione'), ('VIOLENCIA DOMESTICA', 'VIOLÊNCIA DOMÉSTICA'), ('FURTO', 'FURTO'), ('CRIME AMBIENTAL', 'CRIME AMBIENTAL'), ('RACISMO', 'RACISMO'), ('TRANSITO', 'TRÂNSITO'), ('CRIME DE DROGAS', 'CRIME DE DROGAS'), ('OUTROS CRIMES', 'OUTROS CRIMES'), ('LESAO CORPORAL', 'LESÃO CORPORAL'), ('CRIME DE ARMA', 'CRIME DE ARMA'), ('ESTELIONATO', 'ESTELIONATO')], default='selecione', max_length=30, verbose_name='Tipificação penal'),
        ),
        migrations.CreateModel(
            name='AcompCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_responsavel', models.CharField(max_length=200, verbose_name='Técnico responsavel')),
                ('evolucao_percepcoes', models.CharField(max_length=255, verbose_name='Evolução percepções')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_acompanhamento_central', to='core.cidadao')),
            ],
        ),
    ]
