# Generated by Django 5.0.7 on 2024-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_informacoescomplementares_evolucao_percepcoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cidade',
            field=models.CharField(max_length=20, verbose_name='Cidade:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='cor_raca',
            field=models.CharField(choices=[('', 'Selecione'), ('AMARELA', 'Amarela'), ('INDIO', 'Índigena'), ('BRANCO', 'Branca'), ('PARDO', 'Pardo'), ('PRETA', 'Preta')], max_length=8, verbose_name='Cor/Raça:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='endereco',
            field=models.CharField(max_length=80, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='estado',
            field=models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], max_length=19, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='idade',
            field=models.CharField(max_length=3, verbose_name='Idade:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='mae',
            field=models.CharField(max_length=50, verbose_name='Nome da mãe:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='moradia_situacao',
            field=models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('ALUGADO', 'Alugado'), ('CEDIDO', 'Cedido'), ('OCUPACAO', 'Ocupação'), ('IRREGULAR', 'Irregular'), ('SITUACAO DE RUA', 'Situação de rua')], max_length=15, null=True, verbose_name='Situação de moradia, tipo de ocupação:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='moradia_tipo',
            field=models.CharField(blank=True, choices=[('ALVENARIA', 'Alvenaria'), ('MADEIRA', 'Madeira'), ('MISTA', 'Mista')], max_length=9, null=True, verbose_name='Tipo de moradia:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='naturalidade',
            field=models.CharField(max_length=50, verbose_name='Naturalidade:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome completo:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='nome_social',
            field=models.CharField(blank=True, default='Não informado', max_length=80, null=True, verbose_name='Nome social:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='remuneracao',
            field=models.CharField(blank=True, choices=[('Empregado', 'Empregado'), ('Desempregado', 'Desempregado'), ('Trabalhador Rural', 'Trabalhador Rural'), ('Autônomo', 'Autônomo'), ('Funcionario Publico', 'Funcionario Publico'), ('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Afastado/INSS', 'Afastado/INSS'), ('Do lar', 'Do lar'), ('Estudante', 'Estudante')], max_length=20, verbose_name='Remuneração:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='sexo',
            field=models.CharField(choices=[('', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')], default='selecione', max_length=1, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Telefone:'),
        ),
    ]
