# Generated by Django 5.0.7 on 2024-09-05 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_cidadao_cidade_alter_cidadao_cor_raca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompcentral',
            name='data_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='acompcentral',
            name='evolucao_percepcoes',
            field=models.CharField(max_length=255, verbose_name='Evolução/ Demanda/ Percepções:'),
        ),
        migrations.AlterField(
            model_name='acompcentral',
            name='tecnico_responsavel',
            field=models.CharField(max_length=200, verbose_name='Técnico responsavel:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Cpf:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='grau_de_parentesco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grau de parentesco da vitima:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='reincidencia',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, null=True, verbose_name='Relata reincidência?:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='sugest_encaminhamento',
            field=models.CharField(blank=True, choices=[('SASDH', 'SASDH'), ('NATERA-MP', 'NATERA-MP'), ('GRUPO NAA OU AA', 'GRUPO NAA OU AA'), ('INTERNAÇÃO EM COMUNIDADE TERAPÊUTICA', 'INTERNAÇÃO EM COMUNIDADE TERAPÊUTICA'), ('RETIRADA DE DOCUMENTOS-IML', 'RETIRADA DE DOCUMENTOS-IML'), ('CAPS-AD |||/CAPS-SAMAUMA', 'CAPS-AD |||/CAPS-SAMAUMA'), ('OUTROS', 'OUTROS')], max_length=36, null=True, verbose_name='Sugestão de encaminhamento:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='violencia_dome_nome_vitima',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome da vitima de violência domestica:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='violencia_domestica',
            field=models.CharField(blank=True, max_length=50, verbose_name='Em caso de violência domestica:'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='deficiencia',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='É portador de alguma deficiência:'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='drogas_uso',
            field=models.CharField(blank=True, choices=[('ALCOOL', 'Álcool'), ('CIGARRO', 'Cigarro'), ('MACONHA', 'Maconha'), ('PASTA BASE', 'Pasta Base'), ('COCAINA', 'Cocaína'), ('MERLA', 'Merla'), ('CRACK', 'Crack'), ('OUTRAS DROGAS', 'Outras drogas')], max_length=20, null=True, verbose_name='Faz ou já fez uso de:'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='medicacao_controlada_jus',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Especifique o tipo de medicação controlada:'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='tratamento_psi_jus',
            field=models.CharField(max_length=80, verbose_name='Especifique o tratamento psiquiatrico:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='analise_descritiva',
            field=models.CharField(max_length=300, verbose_name='Análise descritiva:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='escolaridade_familiar',
            field=models.CharField(choices=[('SELECIONE', 'Selecione'), ('NAO ESCOLARIZADO', 'Não escolarizado'), ('FUNDAMENTAL INCOMPLETO', 'Fundamental incompleto'), ('FUNDAMENTAL COMPLETO', 'Fundamental completo'), ('MEDIO INCOMPLETO', 'Médio Incompleto'), ('MEDIO COMPLETO', 'Médio Completo'), ('SUPERIOR INCOMPLETO', 'Superior Incompleto'), ('SUPERIOR COMPLETO', 'Superior Completo'), ('POS GRADUAÇÃO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('POS-DOUTORADO', 'Pós Doutorado'), ('NÃO DETERMINADO', 'Não determinado')], default='selecione', max_length=30, verbose_name='Grau de Escolaridade do familiar:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='idade_familiar',
            field=models.CharField(blank=True, max_length=3, verbose_name='Idade do familiar:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='medida_cumprimento',
            field=models.CharField(choices=[('', 'Selecione'), ('COMPARECIMENTO BIMESTRAL', 'COMPARECIMENTO BIMESTRAL'), ('COMPARECIMENTO MENSAL', 'COMPARECIMENTO MENSAL'), ('COMPARECIMENTO QUINZENAL', 'COMPARECIMENTO QUINZENAL'), ('COMPARECIMENTO SEMANAL', 'COMPARECIMENTO SEMANAL'), ('COMPARECIMENTO TRIMESTRAL', 'COMPARECIMENTO TRIMESTRAL'), ('GRUPO REFLEXIVO', 'GRUPO REFLEXIVO'), ('PSC', 'PSC')], default='selecione', max_length=50, verbose_name='Medida de cumprimento:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='motivo_saida',
            field=models.CharField(choices=[('NAO DEFINIDO', 'NÃO DEFINIDO'), ('CUMPRIMENTO INTEGRAL', 'CUMPRIMENTO INTEGRAL'), ('DESCUMPRIMENTO', 'DESCUMPRIMENTO'), ('PRISAO', 'PRISÃO'), ('OUTRO', 'OUTRO')], default='nao definido', max_length=40, verbose_name='Motivo de saida:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='nome_familiar',
            field=models.CharField(max_length=70, verbose_name='Nome de um familiar:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='ocupacao',
            field=models.CharField(max_length=100, verbose_name='Ocupação:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='parentesco',
            field=models.CharField(default='', max_length=100, verbose_name='Grau de parentesco:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='tip_penal',
            field=models.CharField(choices=[('', 'Selecione'), ('VIOLENCIA DOMESTICA', 'VIOLÊNCIA DOMÉSTICA'), ('FURTO', 'FURTO'), ('CRIME AMBIENTAL', 'CRIME AMBIENTAL'), ('RACISMO', 'RACISMO'), ('TRANSITO', 'TRÂNSITO'), ('CRIME DE DROGAS', 'CRIME DE DROGAS'), ('OUTROS CRIMES', 'OUTROS CRIMES'), ('LESAO CORPORAL', 'LESÃO CORPORAL'), ('CRIME DE ARMA', 'CRIME DE ARMA'), ('ESTELIONATO', 'ESTELIONATO')], default='selecione', max_length=30, verbose_name='Tipificação penal:'),
        ),
    ]
