# Generated by Django 5.0.7 on 2024-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_acompcentral_data_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompcentral',
            name='data_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
