# Generated by Django 5.0.7 on 2024-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_acompcentral_evolucao_percepcoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armtime',
            name='time',
            field=models.IntegerField(),
        ),
    ]
