# Generated by Django 5.0.7 on 2024-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_armtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='nome_social',
            field=models.CharField(blank=True, default='Não definido', max_length=80, null=True, verbose_name='Nome social:'),
        ),
    ]
