# Generated by Django 5.0.7 on 2024-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_cidadao_nome_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='data_entrada',
            field=models.CharField(blank=True, default='Não informado', max_length=10),
        ),
    ]
