# Generated by Django 5.0.7 on 2024-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_cidadao_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='data_entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
