# Generated by Django 5.0.7 on 2024-09-20 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_cidadao_data_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armtime',
            name='time',
            field=models.IntegerField(default='', verbose_name='Tempo:'),
        ),
        migrations.CreateModel(
            name='ViolenDomest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_form_viole', models.DateField(default=django.utils.timezone.now)),
                ('enteados', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Tem enteados?')),
                ('religiao', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Pratica alguma religião? Qual?')),
                ('trab_vitima', models.CharField(blank=True, max_length=80, null=True, verbose_name='A vitima trabalhava qual era a profissão?')),
                ('dependencia_fin', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=80, verbose_name='A vitima dependia financeiramente de você?')),
                ('autor_alcool', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='O autor faz uso de álcool?')),
                ('uso_drogas_viole', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='O autor faz uso de drogas? Qual?')),
                ('raça_ident', models.CharField(choices=[('', 'Selecione'), ('AMARELA', 'Amarela'), ('INDIO', 'Índigena'), ('BRANCO', 'Branca'), ('PARDO', 'Pardo'), ('PRETA', 'Preta')], default='Selecione', max_length=8, verbose_name='Com qual cor/raça você se identifica?')),
                ('filhos_agress', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Os filhos já presenciaram alguma agressão?')),
                ('ameacar_suicidio', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='O autor já tentou ou ameçou suicidar-se?')),
                ('dificul_finan', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='O autor está desempregado ou possui dificuldades financeira graves?')),
                ('acesso_armas', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='O autor tem acesso a armas de fogo?')),
                ('relacao_vit', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Que tipo de relação mantém atualmente com a vitima?')),
                ('reconhe_violencia', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Você reconhece que usou de violência(física, psicológica, entre outras) em relação à vitima?')),
                ('arrepen', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Você se sente arrependido?')),
                ('sentim_vitim', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=300, verbose_name='Qual seu sentimento em relação à vitima?')),
                ('passagen_ant', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], default='Selecione', max_length=9, verbose_name='Já passou por esse grupo que trata sobre violência doméstica?')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_violencia_domes', to='core.cidadao')),
            ],
        ),
    ]
