# Generated by Django 5.0.7 on 2024-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_armtime_time_violendomest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violendomest',
            name='data_form_viole',
            field=models.DateField(auto_now_add=True),
        ),
    ]
