# Generated by Django 5.0.7 on 2024-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_violendomest_data_form_viole'),
    ]

    operations = [
        migrations.AddField(
            model_name='violendomest',
            name='process_referente',
            field=models.CharField(default=1, max_length=30, verbose_name='A qual processo isso se refere?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='motivo_saida',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('NAO DEFINIDO', 'NÃO DEFINIDO'), ('CUMPRIMENTO INTEGRAL', 'CUMPRIMENTO INTEGRAL'), ('DESCUMPRIMENTO', 'DESCUMPRIMENTO'), ('PRISAO', 'PRISÃO'), ('OUTRO', 'OUTRO')], default='nao definido', max_length=40, verbose_name='Motivo de saida:'),
        ),
    ]
