# Generated by Django 5.0.7 on 2024-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_violendomest_process_referente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Cpf:'),
        ),
        migrations.AlterField(
            model_name='violendomest',
            name='process_referente',
            field=models.CharField(max_length=30, unique=True, verbose_name='A qual processo isso se refere?'),
        ),
    ]
