# Generated by Django 5.0.7 on 2024-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_cidadao_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocriminal',
            name='ja_esteve_preso',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Já esteve preso?:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='juiz_de_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='Juiz de origem:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='medida_aplicada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Medida aplicada:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='numero_do_processo',
            field=models.CharField(max_length=30, verbose_name='Número do processo:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='prisao_familiar',
            field=models.CharField(blank=True, choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Alguém da sua familia já esteve preso?:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='prisao_justificativa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Por qual motivo esteve preso?:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='tipo_penal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo penal:'),
        ),
        migrations.AlterField(
            model_name='violendomest',
            name='sentim_vitim',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qual seu sentimento em relação à vitima?'),
        ),
        migrations.AddIndex(
            model_name='armtime',
            index=models.Index(fields=['time'], name='core_armtim_time_eea8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='cidadao',
            index=models.Index(fields=['nome'], name='core_cidada_nome_e18cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocriminal',
            index=models.Index(fields=['numero_do_processo'], name='core_histor_numero__ebe118_idx'),
        ),
    ]
