# Generated by Django 5.0.7 on 2024-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_historicocriminal_ja_esteve_preso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violendomest',
            name='religiao',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Pratica alguma religião? Qual?'),
        ),
    ]
