# Generated by Django 5.0.7 on 2024-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_violendomest_religiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violendomest',
            name='uso_drogas_viole',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='O autor faz uso de drogas? Qual?'),
        ),
    ]
