# Generated by Django 5.1.1 on 2024-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_violendomest_uso_drogas_viole'),
    ]

    operations = [
        migrations.AddField(
            model_name='violendomest',
            name='status_process',
            field=models.CharField(choices=[('NAO INFORMADO', 'NAO INFORMADO'), ('ATIVO', 'ATIVO'), ('ARQUIVADO', 'ARQUIVADO')], default='NAO INFORMADO', max_length=13, verbose_name='Status do processo'),
        ),
    ]
