# Generated by Django 5.1.1 on 2024-10-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_violendomest_status_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='violendomest',
            name='tecnico_responsavel',
            field=models.CharField(default=1, max_length=80, verbose_name='Tecnico reponsavel:'),
            preserve_default=False,
        ),
    ]
