# Generated by Django 5.1.1 on 2024-10-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_violendomest_tecnico_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violendomest',
            old_name='tecnico_responsavel',
            new_name='tecnico_responsavel_vio',
        ),
    ]
