# Generated by Django 5.1.1 on 2024-10-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='object_id',
        ),
    ]
