# Generated by Django 5.1.1 on 2024-10-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_activitylog_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
    ]
