# Generated by Django 5.1.1 on 2024-10-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_activitylog_cpf_excluido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='cpf_excluido',
            new_name='cpf',
        ),
    ]
