# Generated by Django 5.1.1 on 2024-10-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_activitylog_nome_excluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='nome_excluido',
        ),
    ]
