# Generated by Django 5.1.1 on 2024-10-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_activitylog_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='cpf',
        ),
    ]
