# Generated by Django 5.1.1 on 2024-10-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_activitylog_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armtime',
            name='process_equal',
        ),
    ]
