# Generated by Django 5.1.1 on 2024-10-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_violendomest_relacao_vit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArmTime',
        ),
    ]
