# Generated by Django 5.1.1 on 2024-10-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='unidade',
            field=models.CharField(choices=[('Não informado', 'Não informado'), ('IAPEN-RB', 'IAPEN-RB'), ('IAPEN-CR', 'IAPEN-CR')], default='Não informado', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='unidade',
            field=models.CharField(choices=[('Não informado', 'Não informado'), ('IAPEN-RB', 'IAPEN-RB'), ('IAPEN-CR', 'IAPEN-CR')], default='Não informado', max_length=15),
        ),
    ]
