# Generated by Django 5.1.1 on 2024-11-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0073_cidadao_unidade_user_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='estado',
            field=models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], default='Não informado', max_length=19, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='remuneracao',
            field=models.CharField(choices=[('Empregado', 'Empregado'), ('Desempregado', 'Desempregado'), ('Trabalhador Rural', 'Trabalhador Rural'), ('Autônomo', 'Autônomo'), ('Funcionario Publico', 'Funcionario Publico'), ('Aposentado', 'Aposentado'), ('Pensionista', 'Pensionista'), ('Afastado/INSS', 'Afastado/INSS'), ('Do lar', 'Do lar'), ('Estudante', 'Estudante')], default='Não informado', max_length=20, verbose_name='Remuneração:'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='renda_individual',
            field=models.CharField(blank=True, choices=[('MENOS DE UM SALARIO MINIMO', 'Menos de um salario minimo'), ('1 SALARIO MINIMO', '1 salario minimo'), ('2 A 3 SALARIOS MINIMOS', '2 a 3 salarios minimos'), ('MAIS DE 4 SALARIOS MINIMOS', 'Mais de 4 salarios minimos'), ('RECEBO BOLSA FAMILIA', 'Recebo bolsa familia'), ('DEPENDO FINANCEIRAMENTE DE OUTRAS PESSOAS', 'Dependo financeiramente de outras pessoas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='sexo',
            field=models.CharField(choices=[('', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='grau_de_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau de parentesco da vitima:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='ja_esteve_preso',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Já esteve preso?:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='juiz_de_origem',
            field=models.CharField(max_length=50, verbose_name='Juiz de origem:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='medida_aplicada',
            field=models.CharField(max_length=50, verbose_name='Medida aplicada:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='prisao_familiar',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Alguém da sua familia já esteve preso?:'),
        ),
        migrations.AlterField(
            model_name='historicocriminal',
            name='violencia_dome_nome_vitima',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da vitima de violência domestica:'),
        ),
        migrations.AlterField(
            model_name='historicosaude',
            name='tratamento_psi_jus',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Especifique o tratamento psiquiatrico:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='escolaridade_familiar',
            field=models.CharField(blank=True, choices=[('SELECIONE', 'Selecione'), ('NAO ESCOLARIZADO', 'Não escolarizado'), ('FUNDAMENTAL INCOMPLETO', 'Fundamental incompleto'), ('FUNDAMENTAL COMPLETO', 'Fundamental completo'), ('MEDIO INCOMPLETO', 'Médio Incompleto'), ('MEDIO COMPLETO', 'Médio Completo'), ('SUPERIOR INCOMPLETO', 'Superior Incompleto'), ('SUPERIOR COMPLETO', 'Superior Completo'), ('POS GRADUAÇÃO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('POS-DOUTORADO', 'Pós Doutorado'), ('NÃO DETERMINADO', 'Não determinado')], max_length=30, null=True, verbose_name='Grau de Escolaridade do familiar:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='idade_familiar',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Idade do familiar:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='parentesco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grau de parentesco:'),
        ),
        migrations.AlterField(
            model_name='informacoescomplementares',
            name='quantas_pessoas',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Quantas pessoas moram com você ? (inclua você na contagem)'),
        ),
        migrations.AddIndex(
            model_name='cidadao',
            index=models.Index(fields=['unidade'], name='core_cidada_unidade_02b496_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['unidade'], name='core_user_unidade_0ddb42_idx'),
        ),
    ]
