# Generated by Django 5.1.1 on 2024-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_cidadao_estado_alter_cidadao_remuneracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento: Ex:(dia/mês/ano)'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='idade',
            field=models.CharField(max_length=2, verbose_name='Idade:'),
        ),
    ]
